version: "3.8"

services:
  app:
    build: .
    # Mount Docker socket so that our app can access Docker stats
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 656M
        reservations:
          cpus: '0.10'
          memory: 56M